// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjQFiEttow41q7grgh3T5txv03i5A2avg',
    appId: '1:758264547680:web:8d790a369241bfa9e83605',
    messagingSenderId: '758264547680',
    projectId: 'bank-c4ed0',
    authDomain: 'bank-c4ed0.firebaseapp.com',
    storageBucket: 'bank-c4ed0.firebasestorage.app',
    measurementId: 'G-WVNQJ5H30D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIf_E1AKXreu4yeFxG93UjfWbWJeifH_0',
    appId: '1:758264547680:android:941638badde16217e83605',
    messagingSenderId: '758264547680',
    projectId: 'bank-c4ed0',
    storageBucket: 'bank-c4ed0.firebasestorage.app',
  );

}